# Publish to GitHub Packages and release the project.
# To trigger, create a tag (not a release) with semantic
# versioning (the tag must start with a v).
#
# git tag -a v0.2 -m "Version 0.2"
# git push --tags
#
# This workflow will automatically:
# - build the project using Maven;
# - publish the built project as a Maven package in the project's
#   Maven repository, at https://maven.zcraft.fr/<repo-name>;
# - create a new draft release;
# - attach the built project to the release.

name: Publish new release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
